CREATE TABLE IF NOT EXISTS REGISTERED_USERS (
    ID UUID PRIMARY KEY,
    USERNAME  VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR(10),
    DOB  VARCHAR(15),
    GENDER  VARCHAR(10),
    COUNTRY  VARCHAR(25),
    CITY  VARCHAR(25),
    CREATED_AT TIMESTAMP,
    MEDICAL INT,
    NEGATIVE INT,
    POSITIVE INT
);

CREATE TABLE IF NOT EXISTS USAGE_HISTORY (
    ID UUID PRIMARY KEY,
    USER_ID UUID NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STRAIN_ID INT,
    STRAIN_NAME VARCHAR(15),
    MEDICAL_RANK INT,
    POSITIVE_RANK INT,
    OVERALL_RANK INT,
    HEARTBEAT_HIGH INT,
    HEARTBEAT_LOW INT,
    HEARTBEAT_AVG INT
);