CREATE TABLE IF NOT EXISTS REGISTERED_USERS (
    ID UUID PRIMARY KEY,
    USERNAME  VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR(10),
    DOB  VARCHAR(15),
    GENDER  VARCHAR(10),
    COUNTRY  VARCHAR(25),
    CITY  VARCHAR(25),
    CREATED_AT TIMESTAMP,
    MEDICAL INT,
    NEGATIVE INT,
    POSITIVE INT
);